app/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .forms import LoginForm
from cam.views import main_view

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('main/', main_view, name='main_view')
    #path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    password = models.TextField(max_length=255)
    
    class Meta:
        db_table = "users"
    

app/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    

app/core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, \
PasswordChangeForm, SetPasswordForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout, \
update_session_auth_hash
#from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from .forms import SignupForm, LoginForm
from .models import Users



def insert_user(userData):
    name = userData['username']
    email = userData['email']
    hashed_password = userData['password1']
    print(hashed_password)
    user = Users(username=name, email=email, password=hashed_password)
    user.save()
    
def check_user(userData):
    print(userData['username'])
    print(userData['password'])



# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def contact(request):
    return render(request, 'core/contact.html')


def user_signup(request):
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            messages.success(request, 'Account created successfully!')
            #form.save()
            insert_user(form.cleaned_data)
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form,
    })
    

    
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST) 
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            print(username)
            print(password)
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, 'Logged in successfully!')
                return redirect('/main/')
    else:
        form = LoginForm()
    return render(request, 'core/login.html', {
        'form': form,
    })
    

def user_logout(request):
    logout(request)
    return redirect('/')
        

    

app/core/templates/core/base.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        {% block imports %}{% endblock %}

        <title>{% block title %}{% endblock %} | Recognition</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="#" class="text-xl font-semibold">Recognition</a>

            {% if messages %}
                {% for message in messages %}
                    <!-- <small class="d-block mt-2 {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</small> -->
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Holy guacamole!</strong> {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                {% endfor %}
            {% endif %}

            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if user.is_authenticated %}
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}     
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

app/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}
    {% if user.is_athenticated %}
        {% include 'cam/main.html' %}
    {% else %}
        <h1>Not Logged in!</h1>
    {% endif %}
{% endblock %}

app/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mv-6 text-3xl">Log in</h1>

        <form method="post" action="." novalidate>
            {% csrf_token %}

                <div class="mb-3">
                    <label class="inline-block mt-4 mb-2">Username</label><br>
                    {{ form.username }}
                </div>

                <div class="mb-3">
                    <label class="inline-block mt-4 mb-2">Password</label><br>
                    {{ form.password }}
                </div>

                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-6 bg-rde-100 rounded-xl">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}

                    </div>
                {% endif %}

                <button class="py-4 px-8 mt-5 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

app/core/templates/core/login_test.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mv-6 text-3xl">Log in</h1>

        <form method="post" action="." novalidate>
            {% csrf_token %}

            {% for fm in form %}
                <div class="form-group">
                    {{ fm.label_tag }}
                    {{ fm }}
                    <small class="form-text text-danger">{{ fm.errors|striptags }}</small>
                </div>
            {% endfor %}

            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="er">{{ error }}</p>
                {% endfor %}
            {% endif %}

                <button class="py-4 px-8 mt-5 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Login</button>
        </form>
    </div>
{% endblock %}